#  $$$$$$\   $$$$$$\  $$\       $$$$$$$\  $$$$$$$$\ $$\   $$\
# $$  __$$\ $$  __$$\ $$ |      $$  __$$\ $$  _____|$$$\  $$ |
# $$ /  \__|$$ /  $$ |$$ |      $$ |  $$ |$$ |      $$$$\ $$ |
# $$ |$$$$\ $$ |  $$ |$$ |      $$ |  $$ |$$$$$\    $$ $$\$$ |
# $$ |\_$$ |$$ |  $$ |$$ |      $$ |  $$ |$$  __|   $$ \$$$$ |
# $$ |  $$ |$$ |  $$ |$$ |      $$ |  $$ |$$ |      $$ |\$$$ |
# \$$$$$$  | $$$$$$  |$$$$$$$$\ $$$$$$$  |$$$$$$$$\ $$ | \$$ |
#  \______/  \______/ \________|\_______/ \________|\__|  \__|
#
#              $$$$$$\   $$$$$$\
#             $$  __$$\ $$  __$$\
#             $$ /  $$ |$$ /  $$ |
#             $$ |  $$ |$$ |  $$ |
#             \$$$$$$$ |\$$$$$$$ |
#              \____$$ | \____$$ |
#             $$\   $$ |$$\   $$ |
#             \$$$$$$  |\$$$$$$  |
#              \______/  \______/
# Developed by STN Studios and maintained by Ruben_Artz.
# Visit our website: https://stn-studios.dev/ or also https://rubenmatias.com/

GOLDEN-GG:
  TEXT-COLOR: '&6'
  TEXT-AUTO-GG: '{Level}{Team Color} %vault_prefix% {Player}&f: &6gg'

# $$$$$$$$\ $$\   $$\ $$$$$$$\
# $$  _____|$$$\  $$ |$$  __$$\
# $$ |      $$$$\ $$ |$$ |  $$ |
# $$$$$\    $$ $$\$$ |$$ |  $$ |
# $$  __|   $$ \$$$$ |$$ |  $$ |
# $$ |      $$ |\$$$ |$$ |  $$ |
# $$$$$$$$\ $$ | \$$ |$$$$$$$  |
# \________|\__|  \__|\_______/