#                                                           Developed by Ruben_Artz
#
#                                                     (MC.STN-STUDIOS.DEV @ (C) 2018-2023)

name: 'GoldenGG'
version: '${version}'
main: 'ruben_artz.spigot.bedwars.GMain'
softdepend: [ 'PlaceholderAPI', 'BedWars1058', 'MBedwars' ]
authors: [ 'Ruben_Artz', 'STN Studios' ]
description: 'Add a color when a player writes gg when winning a game of bedwars'
website: 'https://www.spigotmc.org/resources/95321/'

commands:
  golden:
    description: 'Plugin main command.'
    aliases: [ 'gold' ]
